### ISSUE TITLE
Need to customized store wise

### ISSUE THREAD

**Issue by shyamaH** [mazestricks/Magento2-CreateAcountRedirect#9]
This module is working for my project.
I need to restrict this module for only one store.
Could you please advise me to enable this feature?

Thank you.

**Comment by mazestricks** [comment]
Hello @shyamaH , 

Sorry just saw your comment.  Do you still want me to add this feature in this module? 

Thanks!

**Comment by shyamaH** [comment]
Hello @mazestricks ,
Yes please. I need it. 
Thanks for your response.

**Comment by mazestricks** [comment]
Hello @shyamaH ,

Apologies for the late response. I'm closing this issue now. I have updated the system.xml so that you can restrict this module to a specific store that you want.

Thanks!
